export default [
    [
        { key: "Backquote", str: "`", className: "finger1", },
        { key: "Digit1", str: "1", className: "finger1", },
        { key: "Digit2", str: "2", className: "finger2", },
        { key: "Digit3", str: "3", className: "finger3", },
        { key: "Digit4", str: "4", className: "finger4", },
        { key: "Digit5", str: "5", className: "finger4", },
        { key: "Digit6", str: "6", className: "finger4", },
        { key: "Digit7", str: "7", className: "finger5", },
        { key: "Digit8", str: "8", className: "finger3", },
        { key: "Digit9", str: "9", className: "finger2", },
        { key: "Digit0", str: "0", className: "finger1", },
        { key: "Minus", str: "-", className: "finger1", },
        { key: "Equal", str: "=", className: "finger1", },
        { key: "Backspace", str: "Backsp", className: "", },
    ],
    [
        { key: "Tab", str: "Tab", className: "", },
        { key: "KeyQ", str: "q", className: "finger1", },
        { key: "KeyW", str: "w", className: "finger2", },
        { key: "KeyE", str: "e", className: "finger3", },
        { key: "KeyR", str: "r", className: "finger4", },
        { key: "KeyT", str: "t", className: "finger4", },
        { key: "KeyY", str: "y", className: "finger5", },
        { key: "KeyU", str: "u", className: "finger5", },
        { key: "KeyI", str: "i", className: "finger3", },
        { key: "KeyO", str: "o", className: "finger2", },
        { key: "KeyP", str: "p", className: "finger1", },
        { key: "BracketLeft", str: "[", className: "finger1", },
        { key: "BracketRight", str: "]", className: "finger1", },
        { key: "Backslash", str: "\\", className: "finger1", },
    ],
    [
        { key: "CapsLock", str: "Caps Lock", className: "", },
        { key: "KeyA", str: "a", className: "finger1", },
        { key: "KeyS", str: "s", className: "finger2", },
        { key: "KeyD", str: "d", className: "finger3", },
        { key: "KeyF", str: "f", className: "finger4", },
        { key: "KeyG", str: "g", className: "finger4", },
        { key: "KeyH", str: "h", className: "finger5", },
        { key: "KeyJ", str: "j", className: "finger5", },
        { key: "KeyK", str: "k", className: "finger3", },
        { key: "KeyL", str: "l", className: "finger2", },
        { key: "Semicolon", str: ";", className: "finger1", },
        { key: "Quote", str: "'", className: "finger1", },
        { key: "Enter", str: "Enter", className: "", },
    ],
    [
        { key: "ShiftLeft", str: "Shift", className: "", },
        { key: "KeyZ", str: "z", className: "finger1", },
        { key: "KeyX", str: "x", className: "finger2", },
        { key: "KeyC", str: "c", className: "finger3", },
        { key: "KeyV", str: "v", className: "finger4", },
        { key: "KeyB", str: "b", className: "finger4", },
        { key: "KeyN", str: "n", className: "finger5", },
        { key: "KeyM", str: "m", className: "finger5", },
        { key: "Comma", str: ",", className: "finger3", },
        { key: "Period", str: ".", className: "finger2", },
        { key: "Slash", str: "/", className: "finger1", },
        { key: "ShiftRight", str: "Shift", className: "", },
    ],
    [
        { key: "ControlLeft", str: "Ctrl", className: "", },
        { key: "MetaLeft", str: "Win", className: "", },
        { key: "AltLeft", str: "Alt", className: "", },
        { key: "Space", str: "", className: "finger6", },
        { key: "AltRight", str: "Alt", className: "", },
        { key: "MetaRight", str: "Win", className: "", },
        { key: "ContextMenu", str: "Ctx Menu", className: "", },
        { key: "ControlRight", str: "Ctrl", className: "", },
    ],
];