export default [
    [
        { key: "`", str: "`", completed: false, className: "finger1", },
        { key: "1", str: "1", completed: false, className: "finger1", },
        { key: "2", str: "2", completed: false, className: "finger2", },
        { key: "3", str: "3", completed: false, className: "finger3", },
        { key: "4", str: "4", completed: false, className: "finger4", },
        { key: "5", str: "5", completed: false, className: "finger4", },
        { key: "6", str: "6", completed: false, className: "finger4", },
        { key: "7", str: "7", completed: false, className: "finger5", },
        { key: "8", str: "8", completed: false, className: "finger3", },
        { key: "9", str: "9", completed: false, className: "finger2", },
        { key: "0", str: "0", completed: false, className: "finger1", },
        { key: "-", str: "-", completed: false, className: "finger1", },
        { key: "=", str: "=", completed: false, className: "finger1", },
        { key: "Backspace", str: "Backsp", completed: false, className: "", },
    ],
    [
        { key: "Tab", str: "Tab", completed: false, className: "", },
        { key: "q", str: "q", completed: false, className: "finger1", },
        { key: "w", str: "w", completed: false, className: "finger2", },
        { key: "e", str: "e", completed: false, className: "finger3", },
        { key: "r", str: "r", completed: false, className: "finger4", },
        { key: "t", str: "t", completed: false, className: "finger4", },
        { key: "y", str: "y", completed: false, className: "finger5", },
        { key: "u", str: "u", completed: false, className: "finger5", },
        { key: "i", str: "i", completed: false, className: "finger3", },
        { key: "o", str: "o", completed: false, className: "finger2", },
        { key: "p", str: "p", completed: false, className: "finger1", },
        { key: "[", str: "[", completed: false, className: "finger1", },
        { key: "]", str: "]", completed: false, className: "finger1", },
        { key: "\\", str: "\\", completed: false, className: "finger1", },
    ],
    [
        { key: "CapsLock", str: "Caps Lock", completed: false, className: "", },
        { key: "a", str: "a", completed: false, className: "finger1", },
        { key: "s", str: "s", completed: false, className: "finger2", },
        { key: "d", str: "d", completed: false, className: "finger3", },
        { key: "f", str: "f", completed: false, className: "finger4", },
        { key: "g", str: "g", completed: false, className: "finger4", },
        { key: "h", str: "h", completed: false, className: "finger5", },
        { key: "j", str: "j", completed: false, className: "finger5", },
        { key: "k", str: "k", completed: false, className: "finger3", },
        { key: "l", str: "l", completed: false, className: "finger2", },
        { key: ";", str: ";", completed: false, className: "finger1", },
        { key: "'", str: "'", completed: false, className: "finger1", },
        { key: "Enter", str: "Enter", completed: false, className: "", },
    ],
    [
        { key: "ShiftLeft", str: "Shift", completed: false, className: "", },
        { key: "z", str: "z", completed: false, className: "finger1", },
        { key: "x", str: "x", completed: false, className: "finger2", },
        { key: "c", str: "c", completed: false, className: "finger3", },
        { key: "v", str: "v", completed: false, className: "finger4", },
        { key: "b", str: "b", completed: false, className: "finger4", },
        { key: "n", str: "n", completed: false, className: "finger5", },
        { key: "m", str: "m", completed: false, className: "finger5", },
        { key: ",", str: ",", completed: false, className: "finger3", },
        { key: ".", str: ".", completed: false, className: "finger2", },
        { key: "/", str: "/", completed: false, className: "finger1", },
        { key: "ShiftLeft", str: "Shift", completed: false, className: "", },
    ],
    [
        { key: "ControlLeft", str: "Ctrl", completed: false, className: "", },
        { key: "MetaLeft", str: "Win", completed: false, className: "", },
        { key: "AltLeft", str: "Alt", completed: false, className: "", },
        { key: "Space", str: "", completed: false, className: "finger6", },
        { key: "AltRight", str: "Alt", completed: false, className: "", },
        { key: "MetaRight", str: "Win", completed: false, className: "", },
        { key: "ContextMenu", str: "Ctx Menu", completed: false, className: "", },
        { key: "ControlRight", str: "Ctrl", completed: false, className: "", },
    ],
];